services:
  needlist:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - path: "needlist.dev.env"
    environment:
      MIX_ENV: dev
    depends_on:
      - db
  db:
    image: "postgres:16.4"
    ports:
      - "5432:5432"
    env_file:
      - path: "db.dev.env"
