services:
  needlist:
    build:
      context: .
      args:
        MIX_ENV: dev
    ports:
      - "8080:8080"
    env_file:
      - path: "./envs/dev.env"
      - path: "./envs/dev.local.env"
        required: false
    depends_on:
      - db
  db:
    image: "postgres:16.4"
    ports:
      - "5432:5432"
    env_file:
      - path: "db.dev.env"
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - /var/lib/postgresql/data
